// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfwDWZCtVTkEZWt5UHS-otm2JyY5Bh-w',
    appId: '1:793703257311:web:ec58be6226b22aa3b6856a',
    messagingSenderId: '793703257311',
    projectId: 'task-management-app-8dbca',
    authDomain: 'task-management-app-8dbca.firebaseapp.com',
    storageBucket: 'task-management-app-8dbca.firebasestorage.app',
    measurementId: 'G-SDL428E892',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZLRDUoNZv-TxVaq4UUCGlqEw--qzg-00',
    appId: '1:793703257311:android:bdd40f0bf0799ec5b6856a',
    messagingSenderId: '793703257311',
    projectId: 'task-management-app-8dbca',
    storageBucket: 'task-management-app-8dbca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXxAAUfaBDgm0T1njss8jTSVeJtjEa_I',
    appId: '1:793703257311:ios:c7fd54b3c1e9e242b6856a',
    messagingSenderId: '793703257311',
    projectId: 'task-management-app-8dbca',
    storageBucket: 'task-management-app-8dbca.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXxAAUfaBDgm0T1njss8jTSVeJtjEa_I',
    appId: '1:793703257311:ios:c7fd54b3c1e9e242b6856a',
    messagingSenderId: '793703257311',
    projectId: 'task-management-app-8dbca',
    storageBucket: 'task-management-app-8dbca.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfwDWZCtVTkEZWt5UHS-otm2JyY5Bh-w',
    appId: '1:793703257311:web:f944ad4d50e40e96b6856a',
    messagingSenderId: '793703257311',
    projectId: 'task-management-app-8dbca',
    authDomain: 'task-management-app-8dbca.firebaseapp.com',
    storageBucket: 'task-management-app-8dbca.firebasestorage.app',
    measurementId: 'G-8TEF6T4J8M',
  );

}